#!/usr/bin/env python3
"""Freeze the ratified composition's random realization into Rust const
tables (audio/score.rs input). The Phase 0 rng draws (sparkle rng(5),
keys rng(7), drums rng(3)) were the COMPOSER; the owner ratified one
specific realization — this exports exactly the events that realization
placed, so the Rust port is deterministic data, not a re-roll.

Mirrors the draw ORDER inside synth_audition.py's stem fns 1:1 — if those
fns change, re-run this AND re-audition (a new realization = a new take).
"""

import numpy as np
import phase2_audition as p2  # applies the ratified 8-bar patch on import

BEAT = p2.BEAT


def sparkle_events():
    r = np.random.default_rng(5)
    out = []
    for bar, chord in enumerate(p2.chords8()):
        for beat in r.choice([0.0, 1.5, 2.0, 3.0], size=r.integers(1, 3), replace=False):
            note = int(r.choice(chord)) + 12
            vel = 0.35 + 0.2 * r.random()
            out.append((bar * 4 + beat, note, vel))
    return out


def keys_events():
    r = np.random.default_rng(7)
    out = []
    for bar, chord in enumerate(p2.chords8()):
        pool = chord + [chord[0] + 12, chord[2] + 12]
        for eighth in range(8):
            if r.random() > 0.42:
                continue
            beats = eighth * 0.5 + (0.10 if eighth % 2 else 0.0)
            note = int(r.choice(pool))
            vel = 0.5 + 0.4 * r.random()
            out.append((bar * 4 + beats, note, vel))
    return out


def drum_hat_vels():
    r = np.random.default_rng(3)
    out = []
    for bar in range(p2.LOOP_BARS):
        for eighth in range(8):
            out.append(0.5 + 0.25 * r.random())
    return out


def fmt(rows, kinds):
    return "\n".join(f"    ({', '.join(k % v for k, v in zip(kinds, row))})," if isinstance(row, tuple)
                     else f"    {kinds[0] % row}," for row in rows)


def main():
    sp = sparkle_events()
    ke = keys_events()
    hv = drum_hat_vels()
    print("// generated by export_score (8-bar, ratified p3 realization); do not hand-edit")
    print(f"pub(super) const SPARKLE_SCORE: [(f32, u8, f32); {len(sp)}] = [")
    print(fmt(sp, ("%.2f", "%d", "%.6f")))
    print("];")
    print(f"pub(super) const KEYS_SCORE: [(f32, u8, f32); {len(ke)}] = [")
    print(fmt(ke, ("%.2f", "%d", "%.6f")))
    print("];")
    print(f"pub(super) const DRUM_HAT_VELS: [f32; {len(hv)}] = [")
    print(fmt(hv, ("%.6f",)))
    print("];")


if __name__ == "__main__":
    main()
