//! The FROZEN musical composition (#633 Phase 2). The Phase 0 python's
//! seeded rng was the COMPOSER; the owner ratified one specific realization
//! (the 8-bar `p3_*` renders, 2026-07-16) — these tables ARE that
//! realization's events, so the Rust port is deterministic data, not a
//! re-roll. Regenerate via `export_score` in
//! `docs/superpowers/specs/2026-07-16-ambient-sound-phase0/` — a regen is a
//! NEW take and needs a fresh owner LISTEN gate before it ships.

/// BPM 72 — the ratified lofi tempo.
pub(super) const BPM: f32 = 72.0;
/// 8 bars of 4/4 → the 26.67s loop the owner ratified over the 13.3s v1
/// ("感觉可以拉长一些"): the progression cycles every 4 bars, the melodic
/// foreground (sparkle/keys) varies through all 8.
pub(super) const LOOP_BARS: usize = 8;

pub(super) const BEATS_PER_BAR: f32 = 4.0;

pub(super) fn beat_s() -> f32 {
    60.0 / BPM
}

pub(super) fn loop_secs() -> f32 {
    beat_s() * BEATS_PER_BAR * LOOP_BARS as f32
}

/// Dm7 – Gm7 – B♭maj7 – Am7, one bar each (MIDI), cycled over `LOOP_BARS`.
pub(super) const CHORDS: [[u8; 4]; 4] = [
    [50, 53, 57, 60],
    [55, 58, 62, 65],
    [58, 62, 65, 69],
    [57, 60, 64, 67],
];

pub(super) fn chord_at_bar(bar: usize) -> [u8; 4] {
    CHORDS[bar % CHORDS.len()]
}

// generated by export_score (8-bar, ratified p3 realization); do not hand-edit
pub(super) const SPARKLE_SCORE: [(f32, u8, f32); 11] = [
    (2.00, 65, 0.407160),
    (0.00, 69, 0.360786),
    (5.50, 74, 0.359055),
    (8.00, 70, 0.549835),
    (14.00, 79, 0.436990),
    (17.50, 72, 0.529536),
    (20.00, 74, 0.485338),
    (22.00, 70, 0.362161),
    (27.00, 74, 0.362843),
    (25.50, 81, 0.485836),
    (31.00, 72, 0.529090),
];
pub(super) const KEYS_SCORE: [(f32, u8, f32); 25] = [
    (1.60, 50, 0.849421),
    (2.00, 53, 0.828491),
    (3.60, 57, 0.601948),
    (7.60, 58, 0.564085),
    (8.60, 65, 0.705956),
    (11.60, 58, 0.504718),
    (12.00, 76, 0.580243),
    (12.60, 69, 0.501494),
    (13.60, 67, 0.852133),
    (16.00, 53, 0.716458),
    (17.60, 60, 0.523701),
    (18.00, 60, 0.629215),
    (18.60, 57, 0.651778),
    (21.60, 67, 0.676125),
    (22.00, 55, 0.538682),
    (23.00, 62, 0.768706),
    (23.60, 62, 0.764886),
    (24.00, 77, 0.838030),
    (26.00, 69, 0.871162),
    (27.00, 62, 0.853623),
    (28.60, 76, 0.595796),
    (29.00, 64, 0.850488),
    (30.60, 64, 0.510079),
    (31.00, 69, 0.512140),
    (31.60, 64, 0.763104),
];
pub(super) const DRUM_HAT_VELS: [f32; 64] = [
    0.521412, 0.559203, 0.700319, 0.645541, 0.523532, 0.608282, 0.619763, 0.539935, 0.683644,
    0.528418, 0.597807, 0.629185, 0.607657, 0.646700, 0.684459, 0.739067, 0.571050, 0.662137,
    0.674054, 0.573180, 0.500373, 0.743365, 0.574600, 0.578497, 0.722928, 0.646291, 0.617827,
    0.693319, 0.507587, 0.676741, 0.593561, 0.522713, 0.665125, 0.732866, 0.551798, 0.657523,
    0.574541, 0.685439, 0.680541, 0.554679, 0.707472, 0.664413, 0.670700, 0.705019, 0.607143,
    0.689676, 0.719620, 0.525580, 0.712442, 0.598482, 0.619921, 0.536584, 0.674607, 0.572995,
    0.717785, 0.568844, 0.640452, 0.599914, 0.653227, 0.549160, 0.545072, 0.686715, 0.688056,
    0.641744,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn score_tables_match_the_frozen_realization() {
        // spot-pins + full-table checksums so a regen can't silently ship a
        // different take (review finding: spot-pins alone left KEYS_SCORE /
        // DRUM_HAT_VELS free to drift). The sums bind EVERY entry; the
        // element pins bind the realization's identity.
        assert_eq!(SPARKLE_SCORE[0], (2.00, 65, 0.407_160));
        assert_eq!(KEYS_SCORE[0], (1.60, 50, 0.849_421));
        assert_eq!(DRUM_HAT_VELS[0], 0.521_412);
        assert_eq!(DRUM_HAT_VELS[63], 0.641_744);
        let sum3 = |t: &[(f32, u8, f32)]| {
            t.iter()
                .fold((0.0f64, 0u32, 0.0f64), |(b, n, v), &(bb, nn, vv)| {
                    (b + bb as f64, n + nn as u32, v + vv as f64)
                })
        };
        let (sb, sn, sv) = sum3(&SPARKLE_SCORE);
        assert!((sb - 172.5).abs() < 1e-3 && sn == 800 && (sv - 4.868_63).abs() < 1e-4);
        let (kb, kn, kv) = sum3(&KEYS_SCORE);
        assert!((kb - 461.4).abs() < 1e-3 && kn == 1574 && (kv - 17.052_462).abs() < 1e-4);
        let hv: f64 = DRUM_HAT_VELS.iter().map(|&v| v as f64).sum();
        assert!((hv - 40.091_282).abs() < 1e-4, "hat-vel checksum: {hv}");
        assert!(
            SPARKLE_SCORE.iter().any(|&(b, _, _)| b >= 16.0),
            "the second 4 bars carry fresh sparkle events (the 8-bar variation)"
        );
        assert!(
            KEYS_SCORE.iter().any(|&(b, _, _)| b >= 16.0),
            "the second 4 bars carry fresh keys events"
        );
        assert_eq!(DRUM_HAT_VELS.len(), LOOP_BARS * 8);
        // every scored note is a chord tone (±octave) of its bar's chord —
        // the harmonic invariant that survives any regen
        for &(beats, note, _) in SPARKLE_SCORE.iter().chain(KEYS_SCORE.iter()) {
            let chord = chord_at_bar((beats / BEATS_PER_BAR) as usize);
            assert!(
                chord
                    .iter()
                    .any(|&c| note == c || note == c + 12 || note == c + 24),
                "note {note} at beat {beats} is not a tone of its bar's chord {chord:?}"
            );
        }
    }
}
