//! The FROZEN musical composition (#633 Phase 2). The Phase 0 python's
//! seeded rng was the COMPOSER; the owner ratified one specific realization
//! (the 8-bar `p3_*` renders, 2026-07-16) — these tables ARE that
//! realization's events, so the Rust port is deterministic data, not a
//! re-roll. Regenerate via `export_score` in
//! `docs/superpowers/specs/2026-07-16-ambient-sound-phase0/` — a regen is a
//! NEW take and needs a fresh owner LISTEN gate before it ships.

/// BPM 72 — the ratified lofi tempo.
pub(super) const BPM: f32 = 72.0;
/// 8 bars of 4/4 → the 26.67s loop the owner ratified over the 13.3s v1
/// ("感觉可以拉长一些"): the progression cycles every 4 bars, the melodic
/// foreground (sparkle/keys) varies through all 8.
pub(super) const LOOP_BARS: usize = 8;

pub(super) const BEATS_PER_BAR: f32 = 4.0;

pub(super) fn beat_s() -> f32 {
    60.0 / BPM
}

pub(super) fn loop_secs() -> f32 {
    beat_s() * BEATS_PER_BAR * LOOP_BARS as f32
}

/// Dm7 – Gm7 – B♭maj7 – Am7, one bar each (MIDI), cycled over `LOOP_BARS`.
pub(super) const CHORDS: [[u8; 4]; 4] = [
    [50, 53, 57, 60],
    [55, 58, 62, 65],
    [58, 62, 65, 69],
    [57, 60, 64, 67],
];

pub(super) fn chord_at_bar(bar: usize) -> [u8; 4] {
    CHORDS[bar % CHORDS.len()]
}

// generated by export_score (8-bar, ratified p3 realization); do not hand-edit
pub(super) const SPARKLE_SCORE: [(f32, u8, f32); 11] = [
    (2.00, 65, 0.407160),
    (0.00, 69, 0.360786),
    (5.50, 74, 0.359055),
    (8.00, 70, 0.549835),
    (14.00, 79, 0.436990),
    (17.50, 72, 0.529536),
    (20.00, 74, 0.485338),
    (22.00, 70, 0.362161),
    (27.00, 74, 0.362843),
    (25.50, 81, 0.485836),
    (31.00, 72, 0.529090),
];
pub(super) const KEYS_SCORE: [(f32, u8, f32); 25] = [
    (1.60, 50, 0.849421),
    (2.00, 53, 0.828491),
    (3.60, 57, 0.601948),
    (7.60, 58, 0.564085),
    (8.60, 65, 0.705956),
    (11.60, 58, 0.504718),
    (12.00, 76, 0.580243),
    (12.60, 69, 0.501494),
    (13.60, 67, 0.852133),
    (16.00, 53, 0.716458),
    (17.60, 60, 0.523701),
    (18.00, 60, 0.629215),
    (18.60, 57, 0.651778),
    (21.60, 67, 0.676125),
    (22.00, 55, 0.538682),
    (23.00, 62, 0.768706),
    (23.60, 62, 0.764886),
    (24.00, 77, 0.838030),
    (26.00, 69, 0.871162),
    (27.00, 62, 0.853623),
    (28.60, 76, 0.595796),
    (29.00, 64, 0.850488),
    (30.60, 64, 0.510079),
    (31.00, 69, 0.512140),
    (31.60, 64, 0.763104),
];
pub(super) const DRUM_HAT_VELS: [f32; 64] = [
    0.521412, 0.559203, 0.700319, 0.645541, 0.523532, 0.608282, 0.619763, 0.539935, 0.683644,
    0.528418, 0.597807, 0.629185, 0.607657, 0.646700, 0.684459, 0.739067, 0.571050, 0.662137,
    0.674054, 0.573180, 0.500373, 0.743365, 0.574600, 0.578497, 0.722928, 0.646291, 0.617827,
    0.693319, 0.507587, 0.676741, 0.593561, 0.522713, 0.665125, 0.732866, 0.551798, 0.657523,
    0.574541, 0.685439, 0.680541, 0.554679, 0.707472, 0.664413, 0.670700, 0.705019, 0.607143,
    0.689676, 0.719620, 0.525580, 0.712442, 0.598482, 0.619921, 0.536584, 0.674607, 0.572995,
    0.717785, 0.568844, 0.640452, 0.599914, 0.653227, 0.549160, 0.545072, 0.686715, 0.688056,
    0.641744,
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn score_tables_match_the_frozen_realization() {
        // spot-pins + full-table checksums so a regen can't silently ship a
        // different take (review finding: spot-pins alone left KEYS_SCORE /
        // DRUM_HAT_VELS free to drift). The sums bind EVERY entry; the
        // element pins bind the realization's identity.
        assert_eq!(SPARKLE_SCORE[0], (2.00, 65, 0.407_160));
        assert_eq!(KEYS_SCORE[0], (1.60, 50, 0.849_421));
        assert_eq!(DRUM_HAT_VELS[0], 0.521_412);
        assert_eq!(DRUM_HAT_VELS[63], 0.641_744);
        let sum3 = |t: &[(f32, u8, f32)]| {
            t.iter()
                .fold((0.0f64, 0u32, 0.0f64), |(b, n, v), &(bb, nn, vv)| {
                    (b + bb as f64, n + nn as u32, v + vv as f64)
                })
        };
        let (sb, sn, sv) = sum3(&SPARKLE_SCORE);
        assert!((sb - 172.5).abs() < 1e-3 && sn == 800 && (sv - 4.868_63).abs() < 1e-4);
        let (kb, kn, kv) = sum3(&KEYS_SCORE);
        assert!((kb - 461.4).abs() < 1e-3 && kn == 1574 && (kv - 17.052_462).abs() < 1e-4);
        let hv: f64 = DRUM_HAT_VELS.iter().map(|&v| v as f64).sum();
        assert!((hv - 40.091_282).abs() < 1e-4, "hat-vel checksum: {hv}");
        assert!(
            SPARKLE_SCORE.iter().any(|&(b, _, _)| b >= 16.0),
            "the second 4 bars carry fresh sparkle events (the 8-bar variation)"
        );
        assert!(
            KEYS_SCORE.iter().any(|&(b, _, _)| b >= 16.0),
            "the second 4 bars carry fresh keys events"
        );
        assert_eq!(DRUM_HAT_VELS.len(), LOOP_BARS * 8);
        // every scored note is a chord tone (±octave) of its bar's chord —
        // the harmonic invariant that survives any regen
        for &(beats, note, _) in SPARKLE_SCORE.iter().chain(KEYS_SCORE.iter()) {
            let chord = chord_at_bar((beats / BEATS_PER_BAR) as usize);
            assert!(
                chord
                    .iter()
                    .any(|&c| note == c || note == c + 12 || note == c + 24),
                "note {note} at beat {beats} is not a tone of its bar's chord {chord:?}"
            );
        }
    }
}

// ---------------------------------------------------------------- night
// The NIGHT/RAINY mood track (#644) — Lofi Girl-anchored (measured refs:
// 55-65% power <62Hz, BPM 68-90, onsets 1.2-2/s; LOFI-BIBLE.md), owner
// LISTEN-passed as the v4 realization 2026-07-17 ("这版可以"). Events are
// frozen AT-SECONDS with the humanization (differential swing hats 58% /
// kick 53%, 18ms kick drag, jitter, velocity breathing) baked into the
// timestamps — regenerate via export_night_score.py in the spec dir; a
// regen or BPM change is a NEW take and needs a fresh LISTEN gate.

pub(super) const NIGHT_BPM: f32 = 68.0;
pub(super) const NIGHT_LOOP_BARS: usize = 8;

pub(super) fn night_beat_s() -> f32 {
    60.0 / NIGHT_BPM
}

pub(super) fn night_loop_secs() -> f32 {
    night_beat_s() * BEATS_PER_BAR * NIGHT_LOOP_BARS as f32
}

/// Am7 – Fmaj7 – Cmaj7 – Em7, one bar each, cycled over the 8 bars.
pub(super) const NIGHT_CHORDS: [[u8; 4]; 4] = [
    [57, 60, 64, 67],
    [53, 57, 60, 65],
    [48, 52, 55, 59],
    [52, 55, 59, 62],
];
/// The sub-bass floor per bar (A1 F1 C2 E1) — the measured Lofi Girl
/// signature the day track deliberately lacks.
pub(super) const NIGHT_BASS_ROOTS: [u8; 4] = [33, 29, 36, 28];

pub(super) fn night_chord_at_bar(bar: usize) -> ([u8; 4], u8) {
    (
        NIGHT_CHORDS[bar % NIGHT_CHORDS.len()],
        NIGHT_BASS_ROOTS[bar % NIGHT_BASS_ROOTS.len()],
    )
}

/// Frozen drum event kinds. The night groove deliberately uses only
/// Kick + Hat (no snare backbeat, no open hat: the sleepy register); the
/// day takes carry the full kit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum DrumKind {
    Kick,
    Snare,
    Hat,
    OpenHat,
}

pub(super) const NIGHT_KEYS: [(f32, u8, f32); 6] = [
    (3.9989, 53, 0.501036),
    (5.3155, 53, 0.502335),
    (5.7621, 60, 0.391231),
    (15.0282, 60, 0.354303),
    (20.3087, 57, 0.370914),
    (20.7644, 53, 0.443472),
];
pub(super) const NIGHT_SPARKLE: [(f32, u8, f32); 5] = [
    (2.6471, 79, 0.301661),
    (9.7059, 60, 0.357816),
    (18.5294, 77, 0.376569),
    (23.3824, 71, 0.252749),
    (25.5882, 67, 0.284761),
];
pub(super) const NIGHT_DRUMS: [(f32, DrumKind, f32); 39] = [
    (0.0236, DrumKind::Kick, 0.663799),
    (2.2367, DrumKind::Kick, 0.411038),
    (0.4778, DrumKind::Hat, 0.214931),
    (1.3646, DrumKind::Hat, 0.251454),
    (2.2362, DrumKind::Hat, 0.271023),
    (3.1224, DrumKind::Hat, 0.281255),
    (3.5526, DrumKind::Kick, 0.553927),
    (5.7660, DrumKind::Kick, 0.379583),
    (4.0063, DrumKind::Hat, 0.266364),
    (4.8826, DrumKind::Hat, 0.251054),
    (5.7660, DrumKind::Hat, 0.209403),
    (6.6556, DrumKind::Hat, 0.245932),
    (7.0743, DrumKind::Kick, 0.620215),
    (9.2961, DrumKind::Kick, 0.386612),
    (7.5372, DrumKind::Hat, 0.257124),
    (8.4174, DrumKind::Hat, 0.217017),
    (9.3030, DrumKind::Hat, 0.292058),
    (10.1875, DrumKind::Hat, 0.316476),
    (10.6070, DrumKind::Kick, 0.630006),
    (12.8277, DrumKind::Kick, 0.436625),
    (11.9463, DrumKind::Hat, 0.215210),
    (14.1332, DrumKind::Kick, 0.683702),
    (16.3608, DrumKind::Kick, 0.441433),
    (15.4724, DrumKind::Hat, 0.260578),
    (16.3579, DrumKind::Hat, 0.278973),
    (17.6657, DrumKind::Kick, 0.562252),
    (19.8895, DrumKind::Kick, 0.347772),
    (18.1218, DrumKind::Hat, 0.224934),
    (19.0096, DrumKind::Hat, 0.236696),
    (19.8932, DrumKind::Hat, 0.222340),
    (20.7733, DrumKind::Hat, 0.261781),
    (21.1983, DrumKind::Kick, 0.614736),
    (23.4135, DrumKind::Kick, 0.406885),
    (21.6534, DrumKind::Hat, 0.253510),
    (23.4163, DrumKind::Hat, 0.219788),
    (24.2988, DrumKind::Hat, 0.267106),
    (24.7274, DrumKind::Kick, 0.659486),
    (26.9428, DrumKind::Kick, 0.447755),
    (25.1849, DrumKind::Hat, 0.320593),
];
pub(super) const NIGHT_KICK_TIMES: [f32; 16] = [
    0.0236, 2.2367, 3.5526, 5.7660, 7.0743, 9.2961, 10.6070, 12.8277, 14.1332, 16.3608, 17.6657,
    19.8895, 21.1983, 23.4135, 24.7274, 26.9428,
];

#[cfg(test)]
mod night_tests {
    use super::*;

    #[test]
    fn night_tables_match_the_frozen_v4_realization() {
        // the day tables' drift guard, extended to night (plan item 3 —
        // the review caught it undelivered): sums bind EVERY entry, spot
        // pins bind the identity, and NIGHT_KICK_TIMES is pinned to the
        // Kick entries of NIGHT_DRUMS (two frozen copies of one truth —
        // the texture's baked duck desyncs from the drums if they drift).
        let sum3 = |t: &[(f32, u8, f32)]| {
            t.iter()
                .fold((0.0f64, 0u32, 0.0f64), |(a, n, v), &(aa, nn, vv)| {
                    (a + aa as f64, n + nn as u32, v + vv as f64)
                })
        };
        let (ka, kn, kv) = sum3(&NIGHT_KEYS);
        assert!((ka - 71.1778).abs() < 1e-3 && kn == 336 && (kv - 2.563_291).abs() < 1e-4);
        let (sa, sn, sv) = sum3(&NIGHT_SPARKLE);
        assert!((sa - 79.853).abs() < 1e-3 && sn == 354 && (sv - 1.573_556).abs() < 1e-4);
        let (da, dg) = NIGHT_DRUMS
            .iter()
            .fold((0.0f64, 0.0f64), |(a, g), &(aa, _, gg)| {
                (a + aa as f64, g + gg as f64)
            });
        assert!((da - 495.7997).abs() < 1e-3 && (dg - 14.081_426).abs() < 1e-4);
        assert_eq!(NIGHT_KEYS[0], (3.9989, 53, 0.501_036));
        // the pairing pin: kick times ARE the drums' Kick timestamps
        let mut kicks: Vec<f32> = NIGHT_DRUMS
            .iter()
            .filter(|(_, k, _)| *k == DrumKind::Kick)
            .map(|&(a, _, _)| a)
            .collect();
        kicks.sort_by(f32::total_cmp);
        let mut kt = NIGHT_KICK_TIMES.to_vec();
        kt.sort_by(f32::total_cmp);
        assert_eq!(kicks, kt, "NIGHT_KICK_TIMES desynced from NIGHT_DRUMS");
        // the sleepy register is TABLE content now, not enum shape:
        // DrumKind widened for the day takes' full kit, so pin that night
        // never grows a snare backbeat or open hat
        assert!(
            NIGHT_DRUMS
                .iter()
                .all(|&(_, k, _)| matches!(k, DrumKind::Kick | DrumKind::Hat)),
            "the night groove is kick + closed hat only"
        );
        // harmonic invariant: every night keys note is a chord tone
        for &(at, note, _) in NIGHT_KEYS.iter() {
            let bar = (at / (night_beat_s() * BEATS_PER_BAR)) as usize;
            let (chord, _) = night_chord_at_bar(bar);
            assert!(
                chord.iter().any(|&c| note == c || note == c + 12),
                "night note {note} at {at}s is not a tone of its bar's chord"
            );
        }
    }
}

// ------------------------------------------------------------- day takes
// Additional DAY-mood compositions (the Lofi Girl model: ONE production
// chain, many songs) — owner LISTEN-passed 2026-07-19 ("这两个听感我感觉
// 都挺好的"). Same freeze contract as night: humanization (differential
// swing hats 56% / kick 53%, 15ms kick drag, jitter, velocity breathing,
// played-not-sequenced lead lag) baked into the at-seconds timestamps.
// Regenerate via export_day2_score.py in the spec dir; a regen is a NEW
// take and needs a fresh LISTEN gate. Day 2 "morning": royal-road
// IV-V-iii-vi in C (Fmaj7-G7-Em7-Am7), 76 BPM, boom-bap backbeats on 2&4,
// a hand-written lead motif. Day 3 "golden hour": I-vi-ii-V turnaround
// with voice-led inversions (Cmaj7-Am7/C-Dm7-G7/F), 74 BPM, half-time.

/// Every day take is 8 bars of 4/4 (the anti-fatigue length the original
/// day loop ratified).
pub(super) const DAY_TAKE_LOOP_BARS: usize = 8;

/// One day-mood take's frozen material — what the take-parameterized
/// synth stems read (`synth::day_take_*`). The original day take predates
/// this registry and keeps its dedicated tables/fns above.
pub(super) struct DayTake {
    pub(super) bpm: f32,
    pub(super) chords: &'static [[u8; 4]; 4],
    /// The take's key as pitch classes (0 = C) — the invariant home of the
    /// HAND-WRITTEN lead (`sparkle`), which uses diatonic color beyond the
    /// bar's chord tones (add9 passing tones, next-bar anticipations).
    /// Read only by the frozen-table drift test.
    #[cfg_attr(not(test), allow(dead_code))]
    pub(super) scale_pcs: [u8; 7],
    pub(super) sparkle: &'static [(f32, u8, f32)],
    pub(super) keys: &'static [(f32, u8, f32)],
    pub(super) drums: &'static [(f32, DrumKind, f32)],
}

impl DayTake {
    pub(super) fn beat_s(&self) -> f32 {
        60.0 / self.bpm
    }

    pub(super) fn bar_s(&self) -> f32 {
        self.beat_s() * BEATS_PER_BAR
    }

    pub(super) fn loop_secs(&self) -> f32 {
        self.bar_s() * DAY_TAKE_LOOP_BARS as f32
    }

    pub(super) fn chord_at_bar(&self, bar: usize) -> [u8; 4] {
        self.chords[bar % self.chords.len()]
    }
}

/// C major — both blessed takes sit in C (royal road / I-vi-ii-V).
const C_MAJOR_PCS: [u8; 7] = [0, 2, 4, 5, 7, 9, 11];

pub(super) static DAY2: DayTake = DayTake {
    bpm: DAY2_BPM,
    chords: &DAY2_CHORDS,
    scale_pcs: C_MAJOR_PCS,
    sparkle: &DAY2_SPARKLE,
    keys: &DAY2_KEYS,
    drums: &DAY2_DRUMS,
};

pub(super) static DAY3: DayTake = DayTake {
    bpm: DAY3_BPM,
    chords: &DAY3_CHORDS,
    scale_pcs: C_MAJOR_PCS,
    sparkle: &DAY3_SPARKLE,
    keys: &DAY3_KEYS,
    drums: &DAY3_DRUMS,
};

// generated by export_day2_score A (day2_A_morning, owner LISTEN-passed
// 2026-07-19); do not hand-edit — a regen is a NEW take and needs a
// fresh LISTEN gate
pub(super) const DAY2_BPM: f32 = 76.0;
pub(super) const DAY2_CHORDS: [[u8; 4]; 4] = [
    [53, 57, 60, 64],
    [55, 59, 62, 65],
    [52, 55, 59, 62],
    [57, 60, 64, 67],
];
pub(super) const DAY2_SPARKLE: [(f32, u8, f32); 21] = [
    (1.2049, 69, 0.353715),
    (1.5964, 72, 0.418155),
    (2.3859, 76, 0.426119),
    (3.5613, 74, 0.417228),
    (4.7585, 71, 0.348604),
    (7.1215, 71, 0.409417),
    (8.3073, 74, 0.400514),
    (8.6982, 76, 0.374640),
    (9.8804, 72, 0.406710),
    (11.0609, 69, 0.358630),
    (13.8363, 69, 0.381070),
    (14.2274, 72, 0.426406),
    (15.0173, 76, 0.496389),
    (16.2003, 77, 0.452497),
    (17.3861, 74, 0.412191),
    (18.1779, 71, 0.370362),
    (19.7494, 76, 0.389140),
    (20.9353, 74, 0.387796),
    (22.5183, 72, 0.431502),
    (23.3058, 71, 0.386366),
    (24.0902, 69, 0.334159),
];
pub(super) const DAY2_KEYS: [(f32, u8, f32); 19] = [
    (1.2178, 57, 0.646912),
    (2.0058, 60, 0.492617),
    (2.3807, 72, 0.424631),
    (3.5850, 62, 0.549593),
    (4.3827, 65, 0.699669),
    (5.1584, 59, 0.494263),
    (6.7383, 55, 0.633553),
    (9.5032, 67, 0.581520),
    (11.0642, 69, 0.459770),
    (12.2667, 60, 0.479064),
    (17.7939, 74, 0.580807),
    (18.1809, 55, 0.463651),
    (18.5778, 59, 0.566738),
    (18.9698, 59, 0.602128),
    (19.3716, 62, 0.568490),
    (21.3368, 71, 0.688610),
    (22.1341, 69, 0.533842),
    (22.5223, 69, 0.699207),
    (23.3145, 64, 0.461946),
];
pub(super) const DAY2_DRUMS: [(f32, DrumKind, f32); 85] = [
    (0.0166, DrumKind::Kick, 1.009681),
    (1.8096, DrumKind::Kick, 0.696431),
    (0.7951, DrumKind::Snare, 0.818610),
    (2.3813, DrumKind::Snare, 0.847993),
    (0.0038, DrumKind::Hat, 0.418532),
    (0.4167, DrumKind::Hat, 0.387234),
    (1.5799, DrumKind::Hat, 0.406727),
    (1.9933, DrumKind::Hat, 0.466320),
    (2.3727, DrumKind::Hat, 0.437375),
    (2.7924, DrumKind::Hat, 0.428742),
    (3.1769, DrumKind::Kick, 0.883075),
    (5.1630, DrumKind::Kick, 0.676262),
    (3.9539, DrumKind::Snare, 0.791906),
    (5.5386, DrumKind::Snare, 0.776059),
    (3.9515, DrumKind::Hat, 0.403207),
    (4.3665, DrumKind::Hat, 0.388333),
    (4.7373, DrumKind::Hat, 0.522024),
    (5.1534, DrumKind::Hat, 0.394564),
    (5.5221, DrumKind::Hat, 0.514406),
    (5.9408, DrumKind::Hat, 0.541171),
    (6.3360, DrumKind::Kick, 0.909560),
    (8.1245, DrumKind::Kick, 0.671282),
    (7.1184, DrumKind::Snare, 0.777165),
    (8.6962, DrumKind::Snare, 0.751796),
    (6.7340, DrumKind::Hat, 0.416561),
    (7.1092, DrumKind::Hat, 0.391932),
    (7.5181, DrumKind::Hat, 0.416410),
    (7.8921, DrumKind::Hat, 0.404287),
    (8.3132, DrumKind::Hat, 0.491003),
    (8.6892, DrumKind::Hat, 0.442866),
    (9.1020, DrumKind::Hat, 0.466078),
    (9.4893, DrumKind::Kick, 0.938139),
    (11.4756, DrumKind::Kick, 0.758236),
    (12.4613, DrumKind::Kick, 0.351437),
    (10.2708, DrumKind::Snare, 0.835678),
    (11.8532, DrumKind::Snare, 0.857137),
    (9.4763, DrumKind::Hat, 0.549890),
    (9.8920, DrumKind::Hat, 0.561132),
    (10.2668, DrumKind::Hat, 0.402268),
    (10.6768, DrumKind::Hat, 0.412998),
    (11.4697, DrumKind::Hat, 0.506662),
    (12.2598, DrumKind::OpenHat, 0.433217),
    (12.6506, DrumKind::Kick, 0.939636),
    (14.4340, DrumKind::Kick, 0.721956),
    (13.4287, DrumKind::Snare, 0.788705),
    (15.0115, DrumKind::Snare, 0.816895),
    (12.6272, DrumKind::Hat, 0.543457),
    (13.0500, DrumKind::Hat, 0.402642),
    (13.4254, DrumKind::Hat, 0.485467),
    (13.8347, DrumKind::Hat, 0.447175),
    (14.6345, DrumKind::Hat, 0.559776),
    (14.9978, DrumKind::Hat, 0.477448),
    (15.4205, DrumKind::Hat, 0.432165),
    (15.8018, DrumKind::Kick, 0.945191),
    (17.7946, DrumKind::Kick, 0.718852),
    (16.5916, DrumKind::Snare, 0.812900),
    (18.1640, DrumKind::Snare, 0.812869),
    (15.7932, DrumKind::Hat, 0.548715),
    (16.2037, DrumKind::Hat, 0.466848),
    (17.0002, DrumKind::Hat, 0.453217),
    (17.3647, DrumKind::Hat, 0.516710),
    (17.7869, DrumKind::Hat, 0.555973),
    (18.1614, DrumKind::Hat, 0.449276),
    (18.5705, DrumKind::Hat, 0.448536),
    (18.9655, DrumKind::Kick, 0.916265),
    (20.7542, DrumKind::Kick, 0.709614),
    (19.7446, DrumKind::Snare, 0.783917),
    (21.3284, DrumKind::Snare, 0.808185),
    (18.9488, DrumKind::Hat, 0.473909),
    (19.3598, DrumKind::Hat, 0.514022),
    (19.7392, DrumKind::Hat, 0.520580),
    (20.1580, DrumKind::Hat, 0.367383),
    (20.5219, DrumKind::Hat, 0.538910),
    (20.9503, DrumKind::Hat, 0.391400),
    (21.7369, DrumKind::Hat, 0.419663),
    (22.1219, DrumKind::Kick, 0.947381),
    (24.1126, DrumKind::Kick, 0.687833),
    (25.0897, DrumKind::Kick, 0.332356),
    (22.9056, DrumKind::Snare, 0.832129),
    (24.4798, DrumKind::Snare, 0.773964),
    (22.1012, DrumKind::Hat, 0.536576),
    (23.3174, DrumKind::Hat, 0.507260),
    (24.0970, DrumKind::Hat, 0.415701),
    (24.4752, DrumKind::Hat, 0.462891),
    (24.8879, DrumKind::OpenHat, 0.473727),
];

// generated by export_day2_score B (day2_B_goldenhour, owner
// LISTEN-passed 2026-07-19); do not hand-edit — a regen is a NEW take
// and needs a fresh LISTEN gate
pub(super) const DAY3_BPM: f32 = 74.0;
pub(super) const DAY3_CHORDS: [[u8; 4]; 4] = [
    [48, 52, 55, 59],
    [48, 52, 57, 60],
    [50, 53, 57, 60],
    [53, 55, 59, 62],
];
pub(super) const DAY3_SPARKLE: [(f32, u8, f32); 18] = [
    (0.4268, 76, 0.438005),
    (2.0368, 74, 0.378835),
    (4.0739, 72, 0.370867),
    (5.2854, 69, 0.345576),
    (6.9046, 74, 0.407796),
    (8.1264, 77, 0.465421),
    (10.5533, 71, 0.355927),
    (12.1785, 76, 0.430443),
    (13.3994, 79, 0.427504),
    (14.6133, 76, 0.378083),
    (16.6335, 69, 0.344550),
    (17.4513, 72, 0.360143),
    (18.2642, 76, 0.409813),
    (20.2900, 74, 0.425409),
    (21.4977, 72, 0.340628),
    (23.1284, 71, 0.358504),
    (23.9380, 74, 0.388471),
    (24.7389, 67, 0.323412),
];
pub(super) const DAY3_KEYS: [(f32, u8, f32); 15] = [
    (0.4280, 52, 0.596143),
    (0.8358, 67, 0.499108),
    (2.8656, 67, 0.421223),
    (3.2723, 57, 0.671461),
    (6.1056, 69, 0.457841),
    (6.9251, 62, 0.435186),
    (8.1249, 62, 0.511190),
    (9.3582, 60, 0.442217),
    (10.1681, 53, 0.506639),
    (10.5570, 71, 0.547350),
    (11.3614, 53, 0.556527),
    (13.4044, 67, 0.423811),
    (16.2362, 60, 0.684257),
    (22.7312, 71, 0.487402),
    (23.9609, 55, 0.505008),
];
pub(super) const DAY3_DRUMS: [(f32, DrumKind, f32); 71] = [
    (0.0173, DrumKind::Kick, 1.041377),
    (2.2620, DrumKind::Kick, 0.710965),
    (1.6335, DrumKind::Snare, 0.887970),
    (0.0000, DrumKind::Hat, 0.542069),
    (0.4338, DrumKind::Hat, 0.552801),
    (0.8164, DrumKind::Hat, 0.500973),
    (1.2449, DrumKind::Hat, 0.533661),
    (2.8567, DrumKind::Hat, 0.547940),
    (3.2589, DrumKind::Kick, 0.949922),
    (5.4982, DrumKind::Kick, 0.662980),
    (4.8767, DrumKind::Snare, 0.809161),
    (3.2457, DrumKind::Hat, 0.496492),
    (3.6715, DrumKind::Hat, 0.400565),
    (4.0505, DrumKind::Hat, 0.418058),
    (4.4821, DrumKind::Hat, 0.529811),
    (5.6784, DrumKind::Hat, 0.532754),
    (6.1032, DrumKind::Hat, 0.479453),
    (6.5072, DrumKind::Kick, 0.957047),
    (8.7438, DrumKind::Kick, 0.699603),
    (8.1186, DrumKind::Snare, 0.831246),
    (6.9210, DrumKind::Hat, 0.408869),
    (7.2994, DrumKind::Hat, 0.412246),
    (7.7270, DrumKind::Hat, 0.469696),
    (8.1057, DrumKind::Hat, 0.404850),
    (9.3488, DrumKind::Hat, 0.437897),
    (9.7454, DrumKind::Kick, 1.069742),
    (11.9906, DrumKind::Kick, 0.760676),
    (11.3582, DrumKind::Snare, 0.881988),
    (9.7322, DrumKind::Hat, 0.532468),
    (10.1564, DrumKind::Hat, 0.517827),
    (10.5366, DrumKind::Hat, 0.467206),
    (10.9643, DrumKind::Hat, 0.507164),
    (11.7804, DrumKind::Hat, 0.617869),
    (12.1585, DrumKind::Hat, 0.618095),
    (12.5873, DrumKind::OpenHat, 0.448739),
    (12.9897, DrumKind::Kick, 1.037458),
    (15.2287, DrumKind::Kick, 0.668639),
    (14.6058, DrumKind::Snare, 0.847449),
    (14.2099, DrumKind::Hat, 0.540011),
    (14.5895, DrumKind::Hat, 0.493773),
    (15.0244, DrumKind::Hat, 0.440561),
    (15.4020, DrumKind::Hat, 0.436005),
    (15.8329, DrumKind::Hat, 0.550540),
    (16.2364, DrumKind::Kick, 0.931629),
    (18.4783, DrumKind::Kick, 0.622133),
    (17.8470, DrumKind::Snare, 0.814570),
    (16.2140, DrumKind::Hat, 0.513598),
    (16.6447, DrumKind::Hat, 0.505711),
    (17.0252, DrumKind::Hat, 0.437140),
    (17.4561, DrumKind::Hat, 0.409869),
    (17.8431, DrumKind::Hat, 0.481170),
    (18.2720, DrumKind::Hat, 0.531365),
    (19.0819, DrumKind::Hat, 0.482917),
    (19.4782, DrumKind::Kick, 1.042157),
    (21.7225, DrumKind::Kick, 0.727858),
    (21.0926, DrumKind::Snare, 0.874751),
    (19.4628, DrumKind::Hat, 0.599846),
    (20.2660, DrumKind::Hat, 0.586449),
    (20.7000, DrumKind::Hat, 0.554100),
    (21.0870, DrumKind::Hat, 0.494120),
    (21.8897, DrumKind::Hat, 0.630362),
    (22.3191, DrumKind::Hat, 0.552820),
    (22.7148, DrumKind::Kick, 1.094328),
    (24.9646, DrumKind::Kick, 0.729601),
    (24.3340, DrumKind::Snare, 0.925038),
    (22.7083, DrumKind::Hat, 0.454256),
    (23.5135, DrumKind::Hat, 0.477986),
    (23.9401, DrumKind::Hat, 0.604060),
    (24.7495, DrumKind::Hat, 0.575466),
    (25.1312, DrumKind::Hat, 0.480718),
    (25.5664, DrumKind::OpenHat, 0.586797),
];

#[cfg(test)]
mod day_take_tests {
    use super::*;

    fn sum3(t: &[(f32, u8, f32)]) -> (f64, u32, f64) {
        t.iter()
            .fold((0.0f64, 0u32, 0.0f64), |(a, n, v), &(aa, nn, vv)| {
                (a + aa as f64, n + nn as u32, v + vv as f64)
            })
    }

    fn drum_sums(t: &[(f32, DrumKind, f32)]) -> (f64, f64) {
        t.iter().fold((0.0f64, 0.0f64), |(a, g), &(aa, _, gg)| {
            (a + aa as f64, g + gg as f64)
        })
    }

    /// Sums bind EVERY entry, spot pins bind the identity, and the
    /// harmonic invariant (every scored note is a chord tone ±1-2
    /// octaves of its bar's chord) survives any regen.
    #[test]
    fn day_take_tables_match_the_frozen_realizations() {
        let (sa, sn, sv) = sum3(&DAY2_SPARKLE);
        assert!((sa - 264.0197).abs() < 1e-3 && sn == 1525 && (sv - 8.381_608).abs() < 1e-4);
        let (ka, kn, kv) = sum3(&DAY2_KEYS);
        assert!((ka - 240.5046).abs() < 1e-3 && kn == 1208 && (kv - 10.627_011).abs() < 1e-4);
        let (da, dg) = drum_sums(&DAY2_DRUMS);
        assert!((da - 1069.4331).abs() < 1e-3 && (dg - 50.312_461).abs() < 1e-4);
        assert_eq!(DAY2_SPARKLE[0], (1.2049, 69, 0.353_715));
        assert_eq!(DAY2_KEYS[0], (1.2178, 57, 0.646_912));

        let (sa, sn, sv) = sum3(&DAY3_SPARKLE);
        assert!((sa - 243.5403).abs() < 1e-3 && sn == 1319 && (sv - 6.949_387).abs() < 1e-4);
        let (ka, kn, kv) = sum3(&DAY3_KEYS);
        assert!((ka - 146.3348).abs() < 1e-3 && kn == 926 && (kv - 7.745_362).abs() < 1e-4);
        let (da, dg) = drum_sums(&DAY3_DRUMS);
        assert!((da - 922.5331).abs() < 1e-3 && (dg - 44.375_432).abs() < 1e-4);
        assert_eq!(DAY3_SPARKLE[0], (0.4268, 76, 0.438_005));
        assert_eq!(DAY3_KEYS[0], (0.4280, 52, 0.596_143));

        for take in [&DAY2, &DAY3] {
            // keys are RNG-drawn from the chord pool by construction →
            // strict chord tones (±1-2 octaves)
            for &(at, note, _) in take.keys {
                let chord = take.chord_at_bar((at / take.bar_s()) as usize);
                assert!(
                    chord
                        .iter()
                        .any(|&c| note == c || note == c + 12 || note == c + 24),
                    "keys note {note} at {at}s is not a tone of its bar's chord {chord:?}"
                );
            }
            // the hand-written lead uses diatonic color beyond the bar's
            // chord (add9 passing tones, next-bar anticipations) → the
            // invariant is the take's KEY, not the bar's chord
            for &(at, note, _) in take.sparkle {
                assert!(
                    take.scale_pcs.contains(&(note % 12)),
                    "lead note {note} at {at}s is outside the take's key"
                );
            }
            // the day takes carry the full kit (vs night's kick+hat-only)
            assert!(take.drums.iter().any(|&(_, k, _)| k == DrumKind::Snare));
            assert!(take.drums.iter().any(|&(_, k, _)| k == DrumKind::OpenHat));
            // every event lands inside the loop
            for &(at, _, _) in take.drums {
                assert!(at >= 0.0 && at < take.loop_secs());
            }
        }
    }
}
